# Generated by Django 2.0.13 on 2019-03-27 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
