# Generated by Django 2.0.13 on 2019-03-28 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_companies_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Post',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Company',
            new_name='company',
        ),
    ]
