# Generated by Django 2.0.13 on 2019-04-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190328_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_folder'),
        ),
    ]
