# Generated by Django 2.0.13 on 2019-04-05 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_companies_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments_company', to='blog.Companies'),
        ),
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_company', to='blog.Companies'),
        ),
    ]
